# Analysis Pipeline Notebook

In [60]:
from pymongo import MongoClient
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sklearn.preprocessing import OneHotEncoder
import os

## Pulling Data In

In [61]:
# Load environment variables from env file
load_dotenv()
user = os.getenv("MONGO_USER")
password = os.getenv("MONGO_PASS")
connection_string = f"mongodb+srv://{user}:{password}@cluster0.zqvm7.mongodb.net/?appName=Cluster0"

# creating database connection and collection
client = MongoClient(connection_string)
db = client["sba_loan_project"]
collection = db["loans"]

In [62]:
# Pull data from MongoDB
raw_data = list(collection.find())

# Flatten nested documents into a flat DataFrame
data = pd.json_normalize(raw_data)

# Drop the MongoDB ObjectId field (not useful for analysis)
data.drop(columns=['_id'], inplace=True)

print(data.shape)
data.head()

(418509, 28)

,default,business.state,business.naics_sector,business.naics_description,business.business_type,business.jobs_supported,loan_terms.gross_approval,loan_terms.sba_guaranteed,loan_terms.guarantee_pct,loan_terms.term_months,...,economic_snapshot.state_median_income,economic_snapshot.state_per_capita_income,economic_snapshot.state_gdp,economic_snapshot.national_unemployment,economic_snapshot.fed_funds_rate,economic_snapshot.cpi,economic_snapshot.mortgage_30yr,economic_snapshot.consumer_confidence,economic_snapshot.treasury_10yr,economic_snapshot.unemployment_vs_national
0,0,CA,44,Gasoline Stations with Convenience Stores,INDIVIDUAL,5.0,1562500.0,1406250.0,0.9,300,...,75370.0,43137.0,1938603.3,9.6083,0.175,218.0762,4.6898,71.8417,3.2151,2.7084
1,0,CA,33,Cutlery and Flatware (except Precious) Manufac...,CORPORATION,16.0,38700.0,19350.0,0.5,84,...,75370.0,43137.0,1938603.3,9.6083,0.175,218.0762,4.6898,71.8417,3.2151,2.7084
2,0,TX,23,Masonry Contractors,INDIVIDUAL,15.0,50000.0,25000.0,0.5,84,...,65630.0,38911.0,1255660.8,9.6083,0.175,218.0762,4.6898,71.8417,3.2151,-1.3583
3,0,TX,48,"General Freight Trucking, Local",CORPORATION,2.0,10000.0,5000.0,0.5,84,...,65630.0,38911.0,1255660.8,9.6083,0.175,218.0762,4.6898,71.8417,3.2151,-1.3583
4,1,MO,72,Limited-Service Restaurants,CORPORATION,15.0,210000.0,189000.0,0.9,31,...,63620.0,36984.0,262013.4,9.6083,0.175,218.0762,4.6898,71.8417,3.2151,-0.1916

## Filtering for Analysis

In [63]:
# peeking at one row/document
data.iloc[1]

default                                                                                       0
business.state                                                                               CA
business.naics_sector                                                                        33
business.naics_description                    Cutlery and Flatware (except Precious) Manufac...
business.business_type                                                              CORPORATION
business.jobs_supported                                                                    16.0
loan_terms.gross_approval                                                               38700.0
loan_terms.sba_guaranteed                                                               19350.0
loan_terms.guarantee_pct                                                                    0.5
loan_terms.term_months                                                                       84
loan_terms.interest_rate                                                                    8.6
loan_terms.variable_rate                                                                      0
loan_terms.revolver_status                                                                    0
loan_terms.approval_year                                                                   2010
geography.borrower_state                                                                     CA
geography.bank_in_state                                                                       0
geography.project_in_state                                                                    1
economic_snapshot.state_unemployment                                                    12.3167
economic_snapshot.state_median_income                                                   75370.0
economic_snapshot.state_per_capita_income                                               43137.0
economic_snapshot.state_gdp                                                           1938603.3
economic_snapshot.national_unemployment                                                  9.6083
economic_snapshot.fed_funds_rate                                                          0.175
economic_snapshot.cpi                                                                  218.0762
economic_snapshot.mortgage_30yr                                                          4.6898
economic_snapshot.consumer_confidence                                                   71.8417
economic_snapshot.treasury_10yr                                                          3.2151
economic_snapshot.unemployment_vs_national                                               2.7084
Name: 1, dtype: object

### Dropping unnecessary cols:
- "business.state": Placeholder for pulling in economic data
- "business.naics_description": Text, redundant with sector instead
- "geography.borrower_state": Placeholder for pulling in economic data
- "loan_terms.approval_year": Time is not important to the analysis
- "loan_terms.sba_guaranteed": Redundant with gross approval and guarantee %

In [64]:
overall_analysis_data = data.drop(columns = ['business.state', 'business.naics_description', 'geography.borrower_state','loan_terms.approval_year', 'loan_terms.sba_guaranteed'])

### Encoding categorical variables: 
- "business.naics_sector"
- "business.business_type"

In [65]:
overall_analysis_data['business.business_type'].value_counts()

business.business_type
CORPORATION    365015
INDIVIDUAL      45764
PARTNERSHIP      7712
                   18
Name: count, dtype: int64

In [66]:
# dropping rows(18) with empty business type
overall_analysis_data = overall_analysis_data[overall_analysis_data["business.business_type"].str.strip() != ""].copy()

In [67]:
overall_analysis_data['business.naics_sector'].value_counts()

business.naics_sector
72    53196
23    45373
54    42261
44    40784
62    37771
81    36420
42    22531
48    21836
56    19718
33    16963
45    15948
71    11948
53     9044
31     8564
32     7874
52     7108
11     6948
61     5693
51     5051
49     1519
21     1268
22      344
55      254
92       73
na        2
Name: count, dtype: int64

In [68]:
# dropping rows(2) with na business sector
overall_analysis_data = overall_analysis_data[overall_analysis_data["business.naics_sector"].str.strip() != ""].copy()

In [69]:
categorical_cols = ['business.naics_sector', 'business.business_type']
encoder = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')
encoded_data = encoder.fit_transform(overall_analysis_data[categorical_cols])

# get_feature_names_out() with no arguments
encoded_df = pd.DataFrame(
    encoded_data, 
    columns=encoder.get_feature_names_out(),
    index=overall_analysis_data.index  # preserve the index for concat
)

final_analysis_data = pd.concat(
    [overall_analysis_data.drop(columns=categorical_cols), encoded_df], 
    axis=1
)

print(f"Shape: {final_analysis_data.shape}")
final_analysis_data.head()

Shape: (418491, 47)

,default,business.jobs_supported,loan_terms.gross_approval,loan_terms.guarantee_pct,loan_terms.term_months,loan_terms.interest_rate,loan_terms.variable_rate,loan_terms.revolver_status,geography.bank_in_state,geography.project_in_state,...,business.naics_sector_56,business.naics_sector_61,business.naics_sector_62,business.naics_sector_71,business.naics_sector_72,business.naics_sector_81,business.naics_sector_92,business.naics_sector_na,business.business_type_INDIVIDUAL,business.business_type_PARTNERSHIP
0,0,5.0,1562500.0,0.9,300,6.00,1,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,16.0,38700.0,0.5,84,8.60,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,15.0,50000.0,0.5,84,6.25,1,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,2.0,10000.0,0.5,84,9.75,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,15.0,210000.0,0.9,31,6.00,1,0,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

### Splitting into model A (baseline) and model B (geographic) features

In [70]:
final_analysis_data.columns

Index(['default', 'business.jobs_supported', 'loan_terms.gross_approval',
       'loan_terms.guarantee_pct', 'loan_terms.term_months',
       'loan_terms.interest_rate', 'loan_terms.variable_rate',
       'loan_terms.revolver_status', 'geography.bank_in_state',
       'geography.project_in_state', 'economic_snapshot.state_unemployment',
       'economic_snapshot.state_median_income',
       'economic_snapshot.state_per_capita_income',
       'economic_snapshot.state_gdp',
       'economic_snapshot.national_unemployment',
       'economic_snapshot.fed_funds_rate', 'economic_snapshot.cpi',
       'economic_snapshot.mortgage_30yr',
       'economic_snapshot.consumer_confidence',
       'economic_snapshot.treasury_10yr',
       'economic_snapshot.unemployment_vs_national',
       'business.naics_sector_21', 'business.naics_sector_22',
       'business.naics_sector_23', 'business.naics_sector_31',
       'business.naics_sector_32', 'business.naics_sector_33',
       'business.naics_sector_42', 'business.naics_sector_44',
       'business.naics_sector_45', 'business.naics_sector_48',
       'business.naics_sector_49', 'business.naics_sector_51',
       'business.naics_sector_52', 'business.naics_sector_53',
       'business.naics_sector_54', 'business.naics_sector_55',
       'business.naics_sector_56', 'business.naics_sector_61',
       'business.naics_sector_62', 'business.naics_sector_71',
       'business.naics_sector_72', 'business.naics_sector_81',
       'business.naics_sector_92', 'business.naics_sector_na',
       'business.business_type_INDIVIDUAL',
       'business.business_type_PARTNERSHIP'],
      dtype='object')

In [71]:
# saving target (default)
y = final_analysis_data["default"]

In [72]:
# selecting features for baseline model
baseline_model_features = [
    "business.jobs_supported",
    "loan_terms.gross_approval",
    "loan_terms.guarantee_pct",
    "loan_terms.term_months",
    "loan_terms.interest_rate",
    "loan_terms.variable_rate",
    "loan_terms.revolver_status",

    # encoded categorical features
    "business.naics_sector_21", 'business.naics_sector_22',
    'business.naics_sector_23', 'business.naics_sector_31',
    'business.naics_sector_32', 'business.naics_sector_33',
    'business.naics_sector_42', 'business.naics_sector_44',
    'business.naics_sector_45', 'business.naics_sector_48',
    'business.naics_sector_49', 'business.naics_sector_51',
    'business.naics_sector_52', 'business.naics_sector_53',
    'business.naics_sector_54', 'business.naics_sector_55',
    'business.naics_sector_56', 'business.naics_sector_61',
    'business.naics_sector_62', 'business.naics_sector_71',
    'business.naics_sector_72', 'business.naics_sector_81',
    'business.naics_sector_92', 'business.naics_sector_na',
    'business.business_type_INDIVIDUAL',
    'business.business_type_PARTNERSHIP']

In [73]:
# selecting features for full model
full_model_features = baseline_model_features + [
    # Geographic
    "geography.bank_in_state",
    "geography.project_in_state",
    
    # State-level
    "economic_snapshot.state_unemployment",
    "economic_snapshot.state_median_income",
    "economic_snapshot.state_per_capita_income",
    "economic_snapshot.state_gdp",
    
    # National
    "economic_snapshot.national_unemployment",
    "economic_snapshot.fed_funds_rate",
    "economic_snapshot.cpi",
    "economic_snapshot.mortgage_30yr",
    "economic_snapshot.consumer_confidence",
    "economic_snapshot.treasury_10yr",
    
    # Derived
    "economic_snapshot.unemployment_vs_national",
]

In [74]:
X_baseline = final_analysis_data[baseline_model_features]
X_full = final_analysis_data[full_model_features]

print(f"Target shape: {y.shape}")
print(f"Model A features: {X_baseline.shape[1]}")
print(f"Model B features: {X_full.shape[1]}")

Target shape: (418491,)
Model A features: 33
Model B features: 46

## Modeling

Plans:
- Use logistic regression
- Use XGBoost
- See which one has the biggest performance difference
- Use Random Forest